-- MySQL Script generated by MySQL Workbench
-- Sat Aug 17 10:17:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portfolio` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `portfolio` ;

-- -----------------------------------------------------
-- Table `portfolio`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`card` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `href_url` VARCHAR(255) NULL DEFAULT NULL,
  `project` INT NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `url_card_picture` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `portfolio`.`language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`language` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `logo` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `portfolio`.`card_language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`card_language` (
  `card_id` BIGINT NOT NULL,
  `language_id` BIGINT NOT NULL,
  INDEX `FKe96pt45g0rr7afys0l56rhkww` (`language_id` ASC) VISIBLE,
  INDEX `FKc36fdx5kit6w49ke2ygw566qt` (`card_id` ASC) VISIBLE,
  CONSTRAINT `FKc36fdx5kit6w49ke2ygw566qt`
    FOREIGN KEY (`card_id`)
    REFERENCES `portfolio`.`card` (`id`),
  CONSTRAINT `FKe96pt45g0rr7afys0l56rhkww`
    FOREIGN KEY (`language_id`)
    REFERENCES `portfolio`.`language` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `portfolio`.`careers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`careers` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `date` VARCHAR(255) NULL DEFAULT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `portfolio`.`career_tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`career_tasks` (
  `career_id` BIGINT NOT NULL,
  `tasks` VARCHAR(255) NULL DEFAULT NULL,
  INDEX `FKg44k0i7tedxra2mj5bpwkbbcg` (`career_id` ASC) VISIBLE,
  CONSTRAINT `FKg44k0i7tedxra2mj5bpwkbbcg`
    FOREIGN KEY (`career_id`)
    REFERENCES `portfolio`.`careers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `portfolio`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`project` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `date` VARCHAR(255) NULL DEFAULT NULL,
  `description` LONGTEXT NULL DEFAULT NULL,
  `features` LONGTEXT NULL DEFAULT NULL,
  `video_url` LONGTEXT NULL DEFAULT NULL,
  `progress` LONGTEXT NULL DEFAULT NULL,
  `result` LONGTEXT NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `card_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKqtou0co1u5rgflnw0o9vaot65` (`card_id` ASC) VISIBLE,
  CONSTRAINT `FKslaap3hgt0uwgx4yqa5ny8k1x`
    FOREIGN KEY (`card_id`)
    REFERENCES `portfolio`.`card` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `portfolio`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portfolio`.`skills` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `citation` VARCHAR(255) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `level` INT NOT NULL,
  `skill_type` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  `id_language` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKoapp1600ajg0n8jrvk9ho648d` (`id_language` ASC) VISIBLE,
  CONSTRAINT `FK2d0leh87nqbk0n17vxrfmkmfc`
    FOREIGN KEY (`id_language`)
    REFERENCES `portfolio`.`language` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
